language: java
branches:
  only:
    - master
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  slack:
    rooms:
      bruhritto:pDmh2RiY4DC3iavgQ4WddgjZ
    on_success: always
    on_failure: always